/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkOpeningRestore
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

var _registeredLeafs, _isMac, _clickEventHandler;
class LinkOpeningRestore extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    _registeredLeafs.set(this, new Set());
    _isMac.set(this, navigator.platform.toUpperCase().includes("MAC"));
    _clickEventHandler.set(this, (event) => {
      const target = event.target;
      if (target.tagName !== "A" && !target.classList.contains("cm-hmd-internal-link") && !target.classList.contains("cm-link") && !target.classList.contains("cm-url")) {
        return;
      }
      const modifierKeyPressed = _isMac.get(this) ? event.metaKey : event.ctrlKey;
      const linkText = decodeURIComponent(target.textContent);
      const file = this.app.metadataCache.getFirstLinkpathDest(linkText, "");
      if (event.altKey && event.shiftKey && modifierKeyPressed) {
        if (file) {
          this.app.workspace.openPopoutLeaf().openFile(file);
        }
        event.preventDefault();
        event.stopPropagation();
        return;
      }
      if (event.shiftKey && modifierKeyPressed && !event.altKey) {
        if (file) {
          this.app.workspace.getLeaf("tab").openFile(file);
        }
        event.preventDefault();
        event.stopPropagation();
        return;
      }
      if (modifierKeyPressed && !event.shiftKey && !event.altKey) {
        if (file) {
          this.app.workspace.getLeaf(false).openFile(file);
        }
        event.preventDefault();
        event.stopPropagation();
        return;
      }
      event.preventDefault();
      event.stopPropagation();
    });
  }
  onload() {
    this.app.workspace.on("file-open", () => {
      this.#recheckAllLeafs();
    });
    this.#recheckAllLeafs();
  }
  onunload() {
    _registeredLeafs.get(this).forEach((v) => {
      const editorEl = v.view.containerEl.querySelector(".cm-content");
      this.#removeListenerFromElement(editorEl);
    });
  }
  #recheckAllLeafs() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view.getViewType() === "markdown" && !_registeredLeafs.get(this).has(leaf)) {
        _registeredLeafs.get(this).add(leaf);
        const editorEl = leaf.view.containerEl.querySelector(".cm-content");
        if (!editorEl)
          return;
        this.#addListenerToElement(editorEl);
        const originalUnload = leaf.view.onunload;
        leaf.view.onunload = () => {
          _registeredLeafs.get(this).delete(leaf);
          this.#removeListenerFromElement(editorEl);
          originalUnload();
          leaf.view.onunload = originalUnload;
        };
      }
    });
  }
  #addListenerToElement(element) {
    element.addEventListener("click", _clickEventHandler.get(this), {
      capture: true
    });
  }
  #removeListenerFromElement(element) {
    element.removeEventListener("click", _clickEventHandler.get(this), {
      capture: true
    });
  }
}
_registeredLeafs = new WeakMap();
_isMac = new WeakMap();
_clickEventHandler = new WeakMap();
